export const COPY = {
  ja: {
    tagline: '旅と贈り物のメゾン',
    collections: 'コレクション',
    pieces: (n: number) => `${n}点`,
    askConcierge: 'コンシェルジュに相談する',
    myVisits: 'ご来店予約',
    agentView: 'エージェントビュー',
    agentViewEmpty: 'この画面のツール呼び出しはまだありません。',
    signingIn: 'LINEでサインインしています…',
    signInFailed: 'サインインできませんでした',
    backHome: 'トップへ戻る',
    chooseDate: '日付をお選びください。',
    loading: '読み込み中…',
    retry: 'もう一度',
    personalizable: 'パーソナライズ可',
    stockByBoutique: 'ブティックの在庫',
    inStock: (n: number) => `在庫 ${n}`,
    outOfStock: '在庫なし',
    personalization: 'パーソナライズ',
    leadDays: (n: number) => `お届けまで約${n}日`,
    bookVisit: '来店を予約',
    boutique: 'ブティック',
    date: '日付',
    time: '時間',
    note: 'メッセージ（任意）',
    request: 'リクエストを送る',
    closedOnDate: 'この日は休業日です。別の日をお選びください。',
    requested: 'ブティックの確認待ち',
    confirmed: '確定',
    confirmationSent: '確定 · LINEで送信済み',
    visitRequested: 'リクエストを送りました。ブティックからLINEで確定のご連絡があります。',
    noVisits: 'ご来店予約はまだありません。',
    visitNotFound: 'この予約は見つかりませんでした。',
    concierge: 'コンシェルジュ',
    conciergeIntro: 'ギフト選びやご来店のご予約をお手伝いします。',
    placeholder: 'メッセージを入力',
    send: '送信',
    suggestions: ['旅好きの友人へのギフトを40万円以内で探しています。土曜日の14時に銀座で見られますか？', 'はい、お願いします。'],
    results: (n: number) => `${n}件`,
    // What people see for a tool's error code. The tools' hints are written for agents, so screens don't show them.
    errors: {
      not_found: 'お探しのものは見つかりませんでした。',
      invalid_input: '入力内容をご確認ください。',
      boutique_closed: 'この時間はブティックの営業時間外です。',
      in_the_past: 'もう少し先の日時をお選びください。',
      too_many_open_requests: '確認待ちのご予約が上限に達しています。ブティックの確認後に、新しくご予約いただけます。',
      not_signed_in: 'LINEでサインインしてください。',
      invalid_grant: 'LINEでもう一度サインインしてください。',
      temporarily_unavailable: 'LINEのサインインを確認できませんでした。しばらくしてからもう一度お試しください。',
    },
  },
  en: {
    tagline: 'A house of travel and gifts',
    collections: 'Collections',
    pieces: (n: number) => `${n} pieces`,
    askConcierge: 'Ask the concierge',
    myVisits: 'My visits',
    agentView: 'Agent view',
    agentViewEmpty: 'No tool calls on this screen yet.',
    signingIn: 'Signing in with LINE…',
    signInFailed: 'Sign-in failed',
    backHome: 'Back to the start',
    chooseDate: 'Please choose a date.',
    loading: 'Loading…',
    retry: 'Try again',
    personalizable: 'Personalizable',
    stockByBoutique: 'Stock by boutique',
    inStock: (n: number) => `${n} in stock`,
    outOfStock: 'Out of stock',
    personalization: 'Personalization',
    leadDays: (n: number) => `About ${n} days`,
    bookVisit: 'Book a visit',
    boutique: 'Boutique',
    date: 'Date',
    time: 'Time',
    note: 'Note (optional)',
    request: 'Send request',
    closedOnDate: 'Closed on this day. Please pick another.',
    requested: 'Awaiting the boutique',
    confirmed: 'Confirmed',
    confirmationSent: 'Confirmed · LINE sent',
    visitRequested: 'Request sent. The boutique will confirm on LINE.',
    noVisits: 'No visits yet.',
    visitNotFound: "We couldn't find this visit.",
    concierge: 'Concierge',
    conciergeIntro: 'I can help you choose a gift and book a boutique visit.',
    placeholder: 'Write a message',
    send: 'Send',
    suggestions: ["I'm looking for a gift under ¥400,000 for a friend who travels. Could I see it in Ginza on Saturday at 2 pm?", 'Yes, please.'],
    results: (n: number) => `${n} results`,
    errors: {
      not_found: "We couldn't find that.",
      invalid_input: 'Please check what you entered.',
      boutique_closed: 'The boutique is closed at that time.',
      in_the_past: 'Please choose a later time.',
      too_many_open_requests: 'You have as many visits waiting for a boutique as you can. You can request another once one is confirmed.',
      not_signed_in: 'Please sign in with LINE.',
      invalid_grant: 'Please sign in with LINE again.',
      temporarily_unavailable: "LINE sign-in couldn't be checked. Please try again in a moment.",
    },
  },
} as const;
