export const COPY = {
  ja: {
    tagline: '旅と贈り物のメゾン',
    collections: 'コレクション',
    pieces: (n: number) => `${n}点`,
    askConcierge: 'コンシェルジュに相談する',
    myVisits: 'ご来店予約',
    agentView: 'エージェントビュー',
    agentViewEmpty: 'この画面のツール呼び出しはまだありません。',
    language: '言語',
    signingIn: 'LINEでサインインしています…',
    signInFailed: 'サインインできませんでした',
    backHome: 'トップへ戻る',
    chooseDate: '日付をお選びください。',
    dateTooSoon: '明日以降の日付をお選びください。',
    loading: '読み込み中…',
    retry: 'もう一度',
    personalizable: 'パーソナライズ可',
    stockByBoutique: 'ブティックの在庫',
    inStock: (n: number) => `在庫 ${n}`,
    outOfStock: '在庫なし',
    personalization: 'パーソナライズ',
    // The catalog's personalization kinds, by slug (view_product returns slugs).
    personalizationKinds: {
      'initials-hot-stamp': 'イニシャルの箔押し',
      'hand-painted-stripes': 'ハンドペイントのストライプ',
      'monogram-color': 'お好みの色のモノグラム',
    },
    leadDays: (n: number) => `お届けまで約${n}日`,
    bookVisit: '来店を予約',
    boutique: 'ブティック',
    date: '日付',
    time: '時間',
    note: 'メッセージ（任意）',
    request: 'リクエストを送る',
    closedOnDate: 'この日は休業日です。別の日をお選びください。',
    // A request the boutique's hours refused (boutique_closed), naming the boutique.
    closedAtTime: (boutique: string) => `${boutique}はこの時間、営業時間外です。`,
    close: '閉じる',
    requested: 'ブティックの確認待ち',
    confirmed: '確定',
    confirmationSent: '確定 · LINEで送信済み',
    visitRequested: 'リクエストを送りました。ブティックからLINEで確定のご連絡があります。',
    noVisits: 'ご来店予約はまだありません。',
    visitNotFound: 'この予約は見つかりませんでした。',
    concierge: 'コンシェルジュ',
    conciergeIntro: 'ギフト選びやご来店のご予約をお手伝いします。',
    placeholder: 'メッセージを入力',
    send: '送信',
    // Under a reply that ended with nothing to read, beside `retry`'s button (the concierge page).
    noReply: '返信を受け取れませんでした。',
    suggestions: ['旅好きの友人へのギフトを40万円以内で探しています。土曜日の14時に銀座で見られますか？', 'はい、お願いします。'],
    results: (n: number) => `${n}件`,
    noProducts: 'このコレクションには、まだ商品がありません。',
    // Follows an error's copy when the server named the wait (Retry-After).
    tryAgainIn: (seconds: number) => (seconds < 60 ? `目安は${seconds}秒ほどです。` : `目安は${Math.ceil(seconds / 60)}分ほどです。`),
    // What people see for a tool's error code. The tools' hints are written for agents, so screens don't show them.
    errors: {
      not_found: 'お探しのものは見つかりませんでした。',
      invalid_input: '入力内容をご確認ください。',
      boutique_closed: 'この時間はブティックの営業時間外です。',
      in_the_past: 'もう少し先の日時をお選びください。',
      too_many_open_requests: '確認待ちのご予約が上限に達しています。ブティックの確認後に、新しくご予約いただけます。',
      not_signed_in: 'LINEでサインインしてください。',
      invalid_grant: 'LINEでもう一度サインインしてください。',
      temporarily_unavailable: 'LINEのサインインを確認できませんでした。しばらくしてからもう一度お試しください。',
      network: 'ただいまMaisonに接続できません。通信環境をご確認のうえ、もう一度お試しください。',
      server_error: 'Maisonで問題が発生しました。もう一度お試しください。',
      error: '問題が発生しました。もう一度お試しください。',
    },
  },
  en: {
    tagline: 'A house of travel and gifts',
    collections: 'Collections',
    pieces: (n: number) => `${n} pieces`,
    askConcierge: 'Ask the concierge',
    myVisits: 'My visits',
    agentView: 'Agent view',
    agentViewEmpty: 'No tool calls on this screen yet.',
    language: 'Language',
    signingIn: 'Signing in with LINE…',
    signInFailed: 'Sign-in failed',
    backHome: 'Back to the start',
    chooseDate: 'Please choose a date.',
    dateTooSoon: 'Please choose a date from tomorrow on.',
    loading: 'Loading…',
    retry: 'Try again',
    personalizable: 'Personalizable',
    stockByBoutique: 'Stock by boutique',
    inStock: (n: number) => `${n} in stock`,
    outOfStock: 'Out of stock',
    personalization: 'Personalization',
    personalizationKinds: {
      'initials-hot-stamp': 'Hot-stamped initials',
      'hand-painted-stripes': 'Hand-painted stripes',
      'monogram-color': 'Monogram in your choice of color',
    },
    leadDays: (n: number) => `About ${n} days`,
    bookVisit: 'Book a visit',
    boutique: 'Boutique',
    date: 'Date',
    time: 'Time',
    note: 'Note (optional)',
    request: 'Send request',
    closedOnDate: 'Closed on this day. Please pick another.',
    closedAtTime: (boutique: string) => `${boutique} is closed at that time.`,
    close: 'Close',
    requested: 'Awaiting the boutique',
    confirmed: 'Confirmed',
    confirmationSent: 'Confirmed · LINE sent',
    visitRequested: 'Request sent. The boutique will confirm on LINE.',
    noVisits: 'No visits yet.',
    visitNotFound: "We couldn't find this visit.",
    concierge: 'Concierge',
    conciergeIntro: 'I can help you choose a gift and book a boutique visit.',
    placeholder: 'Write a message',
    send: 'Send',
    noReply: 'No reply came back.',
    suggestions: ["I'm looking for a gift under ¥400,000 for a friend who travels. Could I see it in Ginza on Saturday at 2 pm?", 'Yes, please.'],
    results: (n: number) => `${n} results`,
    noProducts: 'Nothing in this collection yet.',
    // Follows an error's copy when the server named the wait (Retry-After).
    tryAgainIn: (seconds: number) => {
      const [n, unit] = seconds < 60 ? [seconds, 'second'] : [Math.ceil(seconds / 60), 'minute'];
      return `That's about ${n} ${unit}${n === 1 ? '' : 's'}.`;
    },
    errors: {
      not_found: "We couldn't find that.",
      invalid_input: 'Please check what you entered.',
      boutique_closed: 'The boutique is closed at that time.',
      in_the_past: 'Please choose a later time.',
      too_many_open_requests: "You've reached the limit of visit requests waiting for a boutique. You can request another once one is confirmed.",
      not_signed_in: 'Please sign in with LINE.',
      invalid_grant: 'Please sign in with LINE again.',
      temporarily_unavailable: "LINE sign-in couldn't be checked. Please try again in a moment.",
      network: "We can't reach Maison right now. Check the connection and try again.",
      server_error: 'Something went wrong at Maison. Please try again.',
      error: 'Something went wrong. Please try again.',
    },
  },
} as const;
